#CONFIG_GPIO=y
# Logging
CONFIG_LOG=y
CONFIG_PRINTK=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y

# I2C Support
CONFIG_I2C=y

# GPIO Support
CONFIG_GPIO=y

# Increase stack size for main thread
CONFIG_MAIN_STACK_SIZE=2048